travis:
  secure:
    BINSTAR_TOKEN: p1vQw7le0gjDVEa5gTmvibE+kWU/ANxjxVitdCEX/0vFEoCfBGzqkQ2l0Hk80AyapW8i+qIZVxFuJhpAqWk2YZ6AfF0VZkFzD4nPfoiBWAmau66d3jal6TYD8vJAtrDXXmKKEAzUo5qZ71r1lFs3kmYx0e2AIQyP5He3GJmFKObIXGo2PeqvSxRzeiGVAMzfif31YMEJo5DHr5TsQnIjgn0NoKHa9DZCAWE5OBm3iYCoaR/SeCeYcHaCx7lMALl/vtfuNOnFFiOASLBMZdQh+OR5vnw/GRwqkqAyRo4tIPtaO3BzExX07vHkYBmtIn2ZGepQhG96npil0LdxNPpQCGQ3Bxvnw9l7Lui54BdA1V3YnONBfgHRAQ1FBvwdNxKUm58iSUsHWMmNMoGTr0jFZkn6q+rCQv5OyKTeiTXHMIeUIT9tyv4wR4JZELqe2BlPO2mS3x0A0AftRCjQ+bDoFK4PHRU4/F/hyp3HSx/AynybIq5ZnDaH7lE/Qrwl7Um282ZT70ljRbApVPVUW6u01nLA/JBO9R3Nkoji50ySk7jnTwk88WKq+4tfDOqJEmQLgfbDlPydb8EK7rw8Qv2oxioVE7EPD7+QJappw52rbGSjg9r6TqzGaC/ly3wv0NReq2RUCP7Drx2fWzhjzlJFIyO86Vk9v5KAHrzjXBF35Do=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
